specVersion: 1.0.0
name: subql-nodle
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
    options:
      historical: false
      skipTransactions: true
  query:
    name: '@subql/query'
    version: '*'
description: 'Subquery indexer for Nodle network (testnet).'
repository: https://github.com/NodleCode/subquery.git
schema:
  file: ./schema.graphql
network:
  chainId: '0x97da7ede98d7bad4e36b4d734b6055425a3be036da2a332ea5a7037656427a21'
  endpoint: wss://nodle-parachain.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/nodle-parachain-dictionary
chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleUniquesTransferEvent
          kind: substrate/EventHandler
          filter:
            module: uniques
            method: Transferred
        - handler: handleUniquesBurnedEvent
          kind: substrate/EventHandler
          filter:
            module: uniques
            method: Burned
        - handler: handleUniquesDestroyedEvent
          kind: substrate/EventHandler
          filter:
            module: uniques
            method: Destroyed
        - handler: handleUniquesIssuedEvent
          kind: substrate/EventHandler
          filter:
            module: uniques
            method: Issued
        - handler: handleUniquesCreatedEvent
          kind: substrate/EventHandler
          filter:
            module: uniques
            method: Created
        - handler: handleUniquesTransferEvent
          kind: substrate/EventHandler
          filter:
            module: substrateUniques
            method: Transferred
        - handler: handleUniquesBurnedEvent
          kind: substrate/EventHandler
          filter:
            module: substrateUniques
            method: Burned
        - handler: handleUniquesDestroyedEvent
          kind: substrate/EventHandler
          filter:
            module: substrateUniques
            method: Destroyed
        - handler: handleUniquesIssuedEvent
          kind: substrate/EventHandler
          filter:
            module: substrateUniques
            method: Issued
        - handler: handleUniquesCreatedEvent
          kind: substrate/EventHandler
          filter:
            module: substrateUniques
            method: Created
        - handler: handleBalancesTransferEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleNewAccountEvent
          kind: substrate/EventHandler
          filter:
            module: system
            method: NewAccount
        - handler: handleKilledAccountEvent
          kind: substrate/EventHandler
          filter:
            module: system
            method: KilledAccount
